name: depths
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  hooks_riverpod:
  flutter_hooks:
  flutter_use:
  another_flushbar:
  line_icons:
  logger:
  skeletor:
  local_value:
  fpdart:
  freezed_annotation:
  skeletonizer:
  http_mock_adapter:
  go_router:
  sentry:
  sentry_flutter:
  stack_trace:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  freezed:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true

scripts:
  fix: dart fix --apply
  gen: dart run build_runner watch -d
